pipeline {
    agent {
        docker {
            image 'jenkins/slave:lts-jdk11'
        }

    }
    stages {
        stage ('SCM'){
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/Develop']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[url: 'https://github.com/Renatoksh/JenkinsBasicPipeline.git']]])
            }
        }
        stage('Build') {
            steps {
                sh 'donet build "$WORKSPACE/src/EAApp.csproj"'
            }
        }

        stage ('Publish') {
            steps {
                sh 'dotnet publish "$WORKSPACE/src/EAAp.csproj"'
                archiveArtifacts artifacts: 'src/bin/Debug/netcoreapp3.1/publish/*'
            }
        }
    }
    
}